ansible_become_pass: ENC[AES256_GCM,data:KQ+aOt+b+TW9sE9czIE=,iv:Vtp579EpkzVhw+yrAS/o9LzjVlEnqfC8xzsKWJItFOE=,tag:u7JRs3lNi+Q9hg0W2H5TDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age127vrhmu8g8sekvwvv7jkf23txad3cc48l5egvuvvr8tlsvyf2fsqq0y326
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtT1crMm4vOHk0dXk2ekdD
            TFpjOW1xdFdOdkRQNm9FN0E4K3hoOFV5ank0Clc1TzJEVmpLcnhHTUIzM3NTZWR6
            TFhQeXF0Ynp0eXdvQ1R0Z0FkampGaE0KLS0tIHdRaTNrNm9jRXRMU3ZuOExxN0dZ
            MjdwVHZXN2tWMXJQQitGcmtabUEySTQKpF7J+d8M9wXE7Ihkzo9dnHSAgUnh4YWu
            YlHJ4ISr8Jz6o7kmp2w7WOKxYU4wOuMpBX7b3sjPJx4Bkpu6lAE1vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-16T21:27:53Z"
    mac: ENC[AES256_GCM,data:Cl06i+O4F8jHpzZq5Q0Q1jY+3yZjAKEepWO2P/BFEfZXvEeM/QOv4r3qkSpyCC1mvp7M4/fg6nMi9jf95r1RT9cPRRHBvjZgR9BrQpJLvLt2kFW9T/axlaScR+xav8cM1LiB+U1QDbMnvMVQIcUehliXtQWmPpQPqsH9mknix9M=,iv:rJN7f+mHle67KYvhDQBtYAb1NPe9hXrVe4VYVd9vXRo=,tag:RlSTV9oa3ikcJfUV6g23RA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
