apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:QZRfwGT96F8u+ra7,iv:f1ZDEX3a2wTETEftiUiT+REYmDBTtLTOLAOGQVjbhJg=,tag:Fd9KELx1c2vPGLxHpvmLUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age127vrhmu8g8sekvwvv7jkf23txad3cc48l5egvuvvr8tlsvyf2fsqq0y326
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMy9IRnAwM1JZdUNkVkFP
            aGltdHMrWVRqNkFBWUE0YVBHWW9PRG5weFd3CkhLYXFaekVsbXFRN1VVUStuVER1
            L1Ztc3dCamROcmtpUDYzQ0x2V0ppYUEKLS0tIFFmSnJmNmYzWlJKSHdzR2g0V3RR
            TUs4RTlwRFRUbjkycGZoeGNva3UyaGsKV6MOCdnZHOL1CK/A7jeXO+htk8d//72v
            oMbrAAJDglM6e+VTyQfMXYxpl6VAgqF4QHARTu3FXm15GjA/CiJcvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-11T18:48:31Z"
    mac: ENC[AES256_GCM,data:HqX+V78+BvERaAkd8r29GFmNS4Wg291PiMplPRiS2fseI+vtDxkKCziTvMvHBR22Fk9RIC7SN1EP1B7i1yE2mg+85ClNc2aoQtjc+YKm9vaaUfCGteCy5P+GCfN4v73OM6l6IWNB9JGoZFmSyySVD2LZK9uRMpaTtDtP7xGvsF4=,iv:6ybEzrLivCpJT8ajxsZ7d3ah34nTvHKC41Plk3jmXwc=,tag:lg1kr08Cqffgr+rWeHxEXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
